- hosts: docker-ol2
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: "{{ item }}"
    with_items:
      - ansible-role-basepackages
      - ansible-role-docker
      - ansible-role-lvm

- hosts: docker-lvm
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: "{{ item }}"
    with_items:
      - ansible-role-basepackages
      - ansible-role-docker
      - ansible-role-docker-thinpool
