#duos/orsp hosts below
- hosts: gotc-jenkins-slave
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: "{{ item }}"
    with_items:
      - ansible-role-jenkins
