---
- hosts: localhost
  vars:
    provisioner_gitrepos__to_merge:
    - { address: 'https://github.com/broadinstitute/ansible-role-configure.git', name: 'ansible-role-configure', version: 'hf_terra_env'}

  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: ansible-role-configure
    vars:
      branch: "{{ lookup('env','ANSIBLE_BRANCH') }}"
