---
- hosts: localhost
  tasks:
  - import_role:
      name: ansible-role-clone-repos
  - include_role:
      name: ansible-role-configure
    vars:
      branch: "{{ lookup('env','ANSIBLE_BRANCH') }}"
