- hosts: docker-ol2
  tasks:
    - import_role:
        name: ansible-role-clone-repos
    - include_role:
        name: "{{ item }}"
      with_items:
        - ansible-role-local-filesystem
        - ansible-role-os-settings
        - ansible-role-docker

- hosts: jenkins-user
  tasks:
    - import_role:
        name: ansible-role-clone-repos
    - include_role:
        name: "{{ item}}"
      with_items:
        - ansible-role-jenkins-user

- hosts: singlecell-mongo
  tasks:
    - import_role:
        name: ansible-role-clone-repos
    - include_role:
        name: "{{ item}}"
      with_items:
        - ansible-role-docker-service
        - ansible-role-stackdriver

- hosts: singlecell
  tasks:
    - import_role:
        name: ansible-role-clone-repos
    - include_role:
        name: "{{ item}}"
      with_items:
        - ansible-role-stackdriver
