#ansiblepull
- src: https://github.com/broadinstitute/ansible-pull-configure.git
#docker
- src: https://github.com/geerlingguy/ansible-role-docker.git
#lvm
- src: https://github.com/broadinstitute/ansible-manage-lvm.git
#basepacks
- src: https://github.com/broadinstitute/ansible-role-basepackages.git
#lvmthinlpool
- src: https://github.com/broadinstitute/ansible-docker-provision-thinpool.git
