#ansiblepull
- src: https://github.com/broadinstitute/ansible-role-configure.git
#docker
- src: https://github.com/broadinstitute/ansible-role-docker.git
#lvm
- src: https://github.com/broadinstitute/ansible-manage-lvm.git
#basepacks
- src: https://github.com/broadinstitute/ansible-role-basepackages.git
#lvmthinlpool
- src: https://github.com/broadinstitute/ansible-role-docker-thinpool.git
#lvm
- src: https://github.com/broadinstitute/ansible-role-lvm.git
