---
agora-mongo_filesystems__to_merge:
  - device: '/dev/disk/by-id/google-agora-mongo-data-disk'
    mountpoint: '/local/mongodb_data'

agora-mongo_gitrepos__to_merge:
  - { address: 'https://github.com/broadinstitute/ansible-role-docker-service.git', name: 'ansible-role-docker-service', version: '1.0.0' }
