---
docker_service_health_check: 'curl http://localhost:9200/_cat/health'

elasticsearch_filesystems__to_merge:
  - device: '/dev/disk/by-id/google-elasticsearch-data-disk'
    mountpoint: '/local/elasticsearch'

elasticsearch_gitrepos__to_merge:
  - { address: 'https://github.com/broadinstitute/ansible-role-docker-service.git', name: 'ansible-role-docker-service', version: '1.0.0' }
