---
#docker vars
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}-18.09.2-3.el7"
docker_package_state: present
docker_install_compose: true
docker_compose_version: "1.22.0"
docker_compose_path: /usr/local/bin/docker-compose
#thinpool stuff
docker_provision_thinpool_device_name: /dev/sdb
docker_provision_thinpool_size_gb: 20
docker_provision_thinpool_volume_group_name: vg_docker
docker_provision_thinpool_logical_volume_name: docker-pool
