---
#docker vars
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}-18.09.2-3.el7"
docker_package_state: present
docker_install_compose: true
docker_compose_version: "1.22.0"
docker_compose_path: /usr/local/bin/docker-compose
