---
#docker vars
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}-18.09.3-3.el7"
docker_package_state: present
docker_install_compose: true
docker_compose_version: "3.7"
docker_compose_path: /usr/local/bin/docker-compose
#overlay2 disk
lvm_groups:
  - vgname: vg_docker
    disks:
      - /dev/sdb
    create: true
    lvnames:
      - lvname: docker-lvm
        size: 100g
        create: true
        filesystem: xfs
        mount: true
        mntp: /var/lib/docker
manage_lvm: true
#jenkins vars
jenkins_type: "master"
jenkins_version: "2.60.3"
jenkins_admin: dsptechops@broadinstitute.org
apache_url: "duos-jenkins.dsp-techops.broadinstitute.org"
gitrepos:
#docker
  - { address: 'https://github.com/broadinstitute/ansible-role-docker.git', name: 'ansible-role-docker' }
#basepacks
  - { address: 'https://github.com/broadinstitute/ansible-role-basepackages.git', name: 'ansible-role-basepackages' }
#lvm
  - { address: 'https://github.com/broadinstitute/ansible-role-lvm.git', name: 'ansible-role-lvm' }
#stackdriver
  - { address: 'https://github.com/broadinstitute/ansible-role-stackdriver.git', name: 'ansible-role-stackdriver' }
#yumcron
  - { address: 'https://github.com/broadinstitute/ansible-role-yum-cron.git', name: 'ansible-role-yum-cron' }
#sentinelone
  - { address: 'https://github.com/broadinstitute/ansible-role-sentinelone.git', name: 'ansible-role-sentinelone' }
#Jenkins master
  - { address: 'https://github.com/broadinstitute/ansible-role-jenkins.git', name: 'ansible-role-jenkins' }
