---
#jenkins vars
jenkins_type: "slave"

#additional packages
additional_packages:
  - bind-utils
  - google-cloud-sdk
  - curl
  - java-1.8.0-openjdk
  - jq
  - kubectl
  - libcurl-devel
  - libxslt-devel
  - libxml2-devel
  - pyOpenSSL
  - python36
  - python36-pip
  - telnet
  - wget
  - zip

#token copy vars
bucket_path: gs://broad-dsp-techops-tokens/
gcloud_project: broad-dsp-techops
folder: jenkins
dest_path: /etc/
token_name: "vault-token-dsde"
vault_addr: "https://clotho.broadinstitute.org:8200"

#role repos to clone
gotc-jenkins-slave_gitrepos__to_merge:
##basepacks
  - { address: 'https://github.com/broadinstitute/ansible-role-basepackages.git', name: 'ansible-role-basepackages', version: 'master' }
##token Copy
  - { address: 'https://github.com/broadinstitute/ansible-role-token-copy.git', name: 'ansible-role-token-copy', version: 'ra_master_add_gcloud_project' }
##docker
  - { address: 'https://github.com/broadinstitute/ansible-role-docker.git', name: 'ansible-role-docker', version: 'master' }
## sbt
  - { address: 'https://github.com/broadinstitute/ansible-role-sbt.git', name: 'ansible-role-sbt', version: 'master' }
