---
#thinpool stuff
docker_provision_thinpool_device_name: /dev/sdb
docker_provision_thinpool_size_gb: 20
docker_provision_thinpool_volume_group_name: vg_docker
docker_provision_thinpool_logical_volume_name: docker-pool
