---
- name: Clone git repos
  git:
    repo: "{{ item.address }}"
    dest: "{{ rolepath }}/{{ item.name }}"
    clone: yes
    update: yes
    refspec: "{{ item.version }}"
  with_items:
    - "{{ gitrepos }}"
