---
- name: add repos to fact
  set_fact:
    gitrepos_fact: "{{ gitrepos_fact | combine({item.address: item.name}) }}"
  with_items:
    - "{{ gitrepos }}"

- name: Clone git repos
  git:
    repo: "{{ item.address }}"
    dest: "{{ rolepath }}/{{ item.name }}"
    clone: yes
    update: yes
    version: "{{ item.version }}"
  with_items:
    - "{{ gitrepos_fact }}"
