---
- name: get list of gitrepos and add to gitrepos_fact
  set_fact:
    gitrepos: "{{ gitrepos|default([]) + [ {'address': item.address, 'name': item.name, 'version': item.version} ] }}"
  with_items:
   - "{{ gitrepos }}"
#  - debug: msg="{{ gitrepos_fact }}"

- name: Clone git repos
  git:
    repo: "{{ item.address }}"
    dest: "{{ rolepath }}/{{ item.name }}"
    clone: yes
    update: yes
    version: "{{ item.version }}"
  with_items:
   - "{{ gitrepos }}"
