---
- name: make sure ansible_merge_vars is installed
  pip:
    name: ansible_merge_vars
    virtualenv: /usr/local/bin/ansible
    virtualenv_site_packages: yes

- name: Merge user variables
  merge_vars:
    suffix_to_merge: gitrepos__to_merge
    merged_var_name: merged_gitrepos
    expected_type: 'dict'

- name: Clone git repos
  git:
    repo: "{{ item.address }}"
    dest: "{{ rolepath }}/{{ item.name }}"
    clone: yes
    update: yes
    version: "{{ item.version }}"
  with_items:
   - "{{ merged_gitrepos }}"
