---
- name: add repos to fact
  template:
    src: repos.yml.j2
    dest: /tmp/repos.yml
  with_items:
    - "{{ gitrepos }}"

- name: Include vars of repo.yml
  include_vars:
    file: /tmp/repos.yml
    name: gitrepos_rendered

- name: Clone git repos
  git:
    repo: "{{ address }}"
    dest: "{{ rolepath }}/{{ name }}"
    clone: yes
    update: yes
    version: "{{ version }}"
  with_items:
   - "{{ gitrepos_rendered }}"
